pipeline {
    agent any
    tools { 
        maven 'Maven_3.0.2' 
        jdk 'Java_1.8' 
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean compile'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Builder') {
            steps {
                parallel(
                    a: {
                        sh 'mvn package'
                    },
                    b: {
                        sh 'mvn install'
                    }
                )
            }
        }
    }
}
