pipeline {
    agent any
    tools { 
        maven 'Maven_3.0.2' 
        jdk 'Java_1.8' 
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Builder') {
            steps {
                sh 'mvn package'
            }
        }
        stage('Artifact') {
            steps {
                sh 'mvn install'
            }
        }
    }
}
